language: python
python:
  - "3.3"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - nosetests --with-coverage --cover-package=hydrobox
after_success:
  - codecov